# Generated by Django 6.1 on 2026-08-17 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Smart Campus AI Project', max_length=200)),
                ('description', models.TextField(help_text='Project scope and goal')),
                ('max_members', models.IntegerField(default=4)),
                ('complementarity_score', models.IntegerField(default=92)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to='profiles.studentprofile')),
                ('required_skill_categories', models.ManyToManyField(related_name='teams_requiring_category', to='skills.skillcategory')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='teams_requiring_skill', to='skills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEADER', 'Team Lead'), ('BACKEND', 'Backend Engineer'), ('FRONTEND', 'Frontend / UI Specialist'), ('ML_AI', 'AI / ML Specialist'), ('CLOUD', 'Cloud / DevOps Specialist'), ('BUSINESS', 'Product & Business Analyst')], default='BACKEND', max_length=30)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='profiles.studentprofile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
            ],
            options={
                'unique_together': {('team', 'student')},
            },
        ),
    ]
