# Generated by Django 6.1 on 2026-08-17 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('website', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='TechCorp Global', max_length=200)),
                ('industry', models.CharField(default='Artificial Intelligence & Software', max_length=100)),
                ('designation', models.CharField(default='Lead Talent Specialist', max_length=150)),
                ('website', models.URLField(blank=True, default='https://techcorp.example.com')),
                ('company_logo_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80')),
                ('verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(default='Stanford University', max_length=200)),
                ('degree', models.CharField(default='B.Tech Computer Science', max_length=200)),
                ('graduation_year', models.IntegerField(default=2026)),
                ('summary', models.TextField(blank=True, default='Passionate computer science student specializing in AI/ML, backend microservices, and full-stack development. Focused on building evidence-backed engineering projects.')),
                ('overall_skill_score', models.IntegerField(default=88, help_text='Overall evidence-backed score 0-100')),
                ('passport_slug', models.SlugField(max_length=100, unique=True)),
                ('github_url', models.URLField(blank=True, default='https://github.com/alexmorgan')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/in/alexmorgan')),
                ('portfolio_url', models.URLField(blank=True, default='https://alexmorgan.dev')),
                ('avatar_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80')),
                ('profile_completion_pct', models.IntegerField(default=85)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
