# Generated by Django 6.1 on 2026-08-17 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_note', models.TextField(blank=True, help_text='Brief statement linking verified projects to role')),
                ('status', models.CharField(choices=[('APPLIED', 'Application Submitted'), ('UNDER_REVIEW', 'Under Evidence Review'), ('SHORTLISTED', 'Shortlisted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Not Selected')], default='APPLIED', max_length=25)),
                ('match_score_pct_at_apply', models.IntegerField(default=0)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.opportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profiles.studentprofile')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('student', 'opportunity')},
            },
        ),
    ]
