# Generated by Django 6.1 on 2026-08-17 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('INTERNSHIP', 'Internship'), ('JOB', 'Full-Time Job'), ('RESEARCH', 'Research Opportunity'), ('HACKATHON', 'Hackathon'), ('COMPETITION', 'Competition'), ('FREELANCE', 'Freelance / Industry Project'), ('CAMPUS_PROJECT', 'Campus Project'), ('TEAM_OPPORTUNITY', 'Team Opportunity')], default='INTERNSHIP', max_length=30)),
                ('description', models.TextField()),
                ('location', models.CharField(default='San Francisco, CA / Remote', max_length=150)),
                ('location_type', models.CharField(choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ON_SITE', 'On-Site')], default='HYBRID', max_length=20)),
                ('duration', models.CharField(default='3 - 6 Months', max_length=100)),
                ('stipend', models.CharField(default='$3,500 - $5,000 / month', max_length=100)),
                ('experience_level', models.CharField(choices=[('ENTRY', 'Entry-Level / Student'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='ENTRY', max_length=20)),
                ('application_deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='profiles.recruiterprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunitySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('REQUIRED', 'Required Skill'), ('PREFERRED', 'Preferred Skill')], default='REQUIRED', max_length=20)),
                ('min_proficiency_score', models.IntegerField(default=70, help_text='Minimum score 0-100 expected')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_skills', to='opportunities.opportunity')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_requirements', to='skills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='SavedOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_students', to='opportunities.opportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_opportunities', to='profiles.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'opportunity')},
            },
        ),
    ]
