# Generated by Django 6.1 on 2026-08-17 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score_pct', models.IntegerField(default=0)),
                ('skill_coverage_score', models.FloatField(default=0.0)),
                ('evidence_strength_score', models.FloatField(default=0.0)),
                ('project_relevance_score', models.FloatField(default=0.0)),
                ('experience_score', models.FloatField(default=0.0)),
                ('credential_score', models.FloatField(default=0.0)),
                ('explanation_json', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_matches', to='opportunities.opportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_matches', to='profiles.studentprofile')),
            ],
            options={
                'ordering': ['-match_score_pct'],
                'unique_together': {('student', 'opportunity')},
            },
        ),
    ]
