# Generated by Django 6.1 on 2026-08-17 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('COURSEWORK', 'Verified Coursework'), ('PROJECT', 'Practical Project'), ('COMPETITION', 'Hackathon / Competition'), ('CREDENTIAL', 'Micro-Credential / Certificate'), ('GITHUB', 'GitHub Repository'), ('EXPERIENCE', 'Internship / Practical Experience')], default='PROJECT', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(help_text='e.g. Stanford University, Google, Coursera, Major League Hacking', max_length=200)),
                ('issue_date', models.DateField()),
                ('verification_status', models.CharField(choices=[('VERIFIED', 'Verified'), ('PENDING', 'Pending Verification'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='VERIFIED', max_length=20)),
                ('url_or_link', models.URLField(blank=True, help_text='Certificate URL, GitHub repository link, or proof link')),
                ('description', models.TextField(blank=True)),
                ('confidence_level', models.IntegerField(default=90, help_text='Evidence confidence rating percentage 0-100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='profiles.studentprofile')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_by', models.CharField(default='Automated Verification System', max_length=150)),
                ('verification_notes', models.TextField(blank=True, default='Verified via institutional API signature & GitHub repository commit hash check.')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_record', to='evidence.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='SkillEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='ADVANCED', max_length=20)),
                ('score_pct', models.IntegerField(default=85, help_text='Evidence strength score percentage 0-100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidences', models.ManyToManyField(blank=True, related_name='linked_skills', to='evidence.evidence')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evidences', to='skills.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evidences', to='profiles.studentprofile')),
            ],
            options={
                'ordering': ['-score_pct'],
                'unique_together': {('student', 'skill')},
            },
        ),
    ]
